### ISSUE TITLE
Disable double tap zoom

### ISSUE THREAD

**Issue by Pospelove** [skyrim-multiplayer/skymp#367]
We do not need double-tap zoom in our in-game interface. 
This code piece may help:
```css
body{
    touch-action: manipulation;
}
```
https://stackoverflow.com/questions/59732074/disable-double-tap-zoom-on-safari-ios-13/59732654#59732654

they say it's for safari, but seems to help even on chromium
